services:
  bypasscors:
    image: drannoc/bypasscors
    ports: 
    - 8080:8080
  
  logchest:
    image: drannoc/logchest
    volumes:
      - .tmp/:/usr/src/logchest
    user: "1000:1000"
    ports:
    - 8081:8081