export default {
    EXPO_PUBLIC_LOGCHEST_ENDPOINT: process.env.EXPO_PUBLIC_LOGCHEST_ENDPOINT || "",
    EXPO_PUBLIC_BYPASSCORS_ENDPOINT: process.env.EXPO_PUBLIC_BYPASSCORS_ENDPOINT || "",
    EXPO_PUBLIC_PANYA_ENDPOINT: process.env.EXPO_PUBLIC_PANYA_ENDPOINT || "",
    EXPO_PUBLIC_IDENTITY_ENDPOINT: process.env.EXPO_PUBLIC_IDENTITY_ENDPOINT || "",
}